
(djangoPy3Env) C:\Users\sabin\OneDrive\Desktop\Dojo_Assignments\Python\django\django_orm\dojo_ninjas_proj>python manage.py shell
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from dojo_ninjas_app.models import *
>>> d1.__dict__
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'd1' is not defined
>>> d1 = Dojo.objects.create(name="Dojo", city="Chicago", state="IA"
... d1 = Dojo.objects.create(name="Dojo", city="Chicago", state="IA")
  File "<console>", line 2
    d1 = Dojo.objects.create(name="Dojo", city="Chicago", state="IA")
     ^
SyntaxError: invalid syntax
>>> d1 = Dojo.objects.create(name="Dojo", city="Chicago", state="IA")
>>> d1.__dict__
{'_state': <django.db.models.base.ModelState object at 0x0000028685950240>, 'id': 10, 'name': 'Dojo', 'city': 'Chicago', 'state': 'IA', 'created_at': datetime.datetime(2021, 3, 22, 3, 25, 5, 966723, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 25, 5, 966723, tzinfo=<UTC>), 'desc': 'old dojo'}
>>> d1.ninjas.all().values()
<QuerySet []>
>>> d1.dave()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Dojo' object has no attribute 'dave'
>>> d1.save()
>>> d2 = Dojo.objects.create(name="Brooklyn", city="New York", state="MA")
>>> d2.save()
>>> d3= Dojo.objects.create(name="Cookie", city="Brooklyn", state="IA")
>>> d3.save()
>>> Dojo.objects.all().values()
<QuerySet [{'id': 7, 'name': 'Dojo1', 'city': 'New York', 'state': 'NY', 'created_at': datetime.datetime(2021, 3, 22, 2, 35, 58, 459525, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 2, 35, 58, 459525, tzinfo=<UTC>), 'desc': '2'}, {'id': 8, 'name': 'Dojo2', 'city': 'Moscow', 'state': 'MA', 'created_at': datetime.datetime(2021, 3, 22, 2, 37, 35, 532529, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 2, 37, 35, 532529, tzinfo=<UTC>), 'desc': '2'}, {'id': 9, 'name': 'Dojo3', 'city': 'Brooklyn', 'state': 'WA', 'created_at': datetime.datetime(2021, 3, 22, 2, 38, 34, 450100, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 2, 38, 34, 450100, tzinfo=<UTC>), 'desc': '2'}, {'id': 10, 'name': 'Dojo', 'city': 'Chicago', 'state': 'IA', 'created_at': datetime.datetime(2021, 3, 22, 3, 25, 5, 966723, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 41, 0, 422948, tzinfo=<UTC>), 'desc': 'old dojo'}, {'id': 11, 'name': 'Brooklyn', 'city': 'New York', 'state': 'MA', 'created_at': datetime.datetime(2021, 3, 22, 3, 41, 58, 496463, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 42, 5, 753289, tzinfo=<UTC>), 'desc': 'old dojo'}, {'id': 12, 'name': 'Cookie', 'city': 'Brooklyn', 'state': 'IA', 'created_at': datetime.datetime(2021, 3, 22, 3, 43, 2, 908219, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 43, 10, 474968, tzinfo=<UTC>), 'desc': 'old dojo'}]>
>>> n1=Ninja.objects.create(first_name="Pizza", last_name="Margarita", ninjas=d1
... n1=Ninja.objects.create(first_name="Pizza", last_name="Margarita", ninjas=d1)
  File "<console>", line 2
    n1=Ninja.objects.create(first_name="Pizza", last_name="Margarita", ninjas=d1)
     ^
SyntaxError: invalid syntax
>>> n1=Ninja.objects.create(first_name="Pizza", last_name="Margarita", dojo=d1)
>>> n1.save()
>>> n1=Ninja.objects.create(first_name="Sausage", last_name="Peperroni", dojo=d1)
>>> n1.save()
>>> n1=Ninja.objects.create(first_name="Vacation", last_name="Beach", dojo=d1)
>>> Dojo.objects.all().values()
<QuerySet [{'id': 7, 'name': 'Dojo1', 'city': 'New York', 'state': 'NY', 'created_at': datetime.datetime(2021, 3, 22, 2, 35, 58, 459525, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 2, 35, 58, 459525, tzinfo=<UTC>), 'desc': '2'}, {'id': 8, 'name': 'Dojo2', 'city': 'Moscow', 'state': 'MA', 'created_at': datetime.datetime(2021, 3, 22, 2, 37, 35, 532529, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 2, 37, 35, 532529, tzinfo=<UTC>), 'desc': '2'}, {'id': 9, 'name': 'Dojo3', 'city': 'Brooklyn', 'state': 'WA', 'created_at': datetime.datetime(2021, 3, 22, 2, 38, 34, 450100, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 2, 38, 34, 450100, tzinfo=<UTC>), 'desc': '2'}, {'id': 10, 'name': 'Dojo', 'city': 'Chicago', 'state': 'IA', 'created_at': datetime.datetime(2021, 3, 22, 3, 25, 5, 966723, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 41, 0, 422948, tzinfo=<UTC>), 'desc': 'old dojo'}, {'id': 11, 'name': 'Brooklyn', 'city': 'New York', 'state': 'MA', 'created_at': datetime.datetime(2021, 3, 22, 3, 41, 58, 496463, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 42, 5, 753289, tzinfo=<UTC>), 'desc': 'old dojo'}, {'id': 12, 'name': 'Cookie', 'city': 'Brooklyn', 'state': 'IA', 'created_at': datetime.datetime(2021, 3, 22, 3, 43, 2, 908219, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 43, 10, 474968, tzinfo=<UTC>), 'desc': 'old dojo'}]>
>>> Ninjas.object.all().values()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Ninjas' is not defined
>>> d1.ninjas.all().values()
<QuerySet [{'id': 12, 'first_name': 'Pizza', 'last_name': 'Margarita', 'dojo_id': 10, 'created_at': datetime.datetime(2021, 3, 22, 3, 46, 48, 70568, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 46, 57, 882867, tzinfo=<UTC>)}, {'id': 13, 'first_name': 'Sausage', 'last_name': 'Peperroni', 'dojo_id': 10, 'created_at': datetime.datetime(2021, 3, 22, 3, 47, 28, 267448, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 47, 37, 21147, tzinfo=<UTC>)}, {'id': 14, 'first_name': 'Vacation', 'last_name': 'Beach', 'dojo_id': 10, 'created_at': datetime.datetime(2021, 3, 22, 3, 48, 9, 819451, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 48, 9, 819451, tzinfo=<UTC>)}]>
>>> d1.ninjas.save()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'RelatedManager' object has no attribute 'save'
>>> ninjas.save()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'ninjas' is not defined
>>> n1.save()
>>> n2=Ninja.objects.create(first_name="Pet", last_name="Puppy", dojo=d2)
>>> n2=Ninja.objects.create(first_name="Cat", last_name="Kitten", dojo=d2)
>>> n2=Ninja.objects.create(first_name="Steve", last_name="Margos", dojo=d2)
>>> n2.save()
>>> d2.ninjas.all().values()
<QuerySet [{'id': 15, 'first_name': 'Pet', 'last_name': 'Puppy', 'dojo_id': 11, 'created_at': datetime.datetime(2021, 3, 22, 3, 51, 31, 137506, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 51, 31, 137506, tzinfo=<UTC>)}, {'id': 16, 'first_name': 'Cat', 'last_name': 'Kitten', 'dojo_id': 11, 'created_at': datetime.datetime(2021, 3, 22, 3, 51, 53, 467024, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 51, 53, 467024, tzinfo=<UTC>)}, {'id': 17, 'first_name': 'Steve', 'last_name': 'Margos', 'dojo_id': 11, 'created_at': datetime.datetime(2021, 3, 22, 3, 52, 16, 226987, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 52, 20, 807485, tzinfo=<UTC>)}]>
>>> n3=Ninja.objects.create(first_name="Weather", last_name="Sunny", dojo=d3)
>>> n3=Ninja.objects.create(first_name="Mexico", last_name="Mojito", dojo=d3)
>>> n3=Ninja.objects.create(first_name="Miami", last_name="Florida", dojo=d3)
>>> n3.save()
>>> d3.ninjas.all().values()
<QuerySet [{'id': 18, 'first_name': 'Weather', 'last_name': 'Sunny', 'dojo_id': 12, 'created_at': datetime.datetime(2021, 3, 22, 3, 53, 22, 515881, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 53, 22, 515881, tzinfo=<UTC>)}, {'id': 19, 'first_name': 'Mexico', 'last_name': 'Mojito', 'dojo_id': 12, 'created_at': datetime.datetime(2021, 3, 22, 3, 53, 46, 714843, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 53, 46, 714843, tzinfo=<UTC>)}, {'id': 20, 'first_name': 'Miami', 'last_name': 'Florida', 'dojo_id': 12, 'created_at': datetime.datetime(2021, 3, 22, 3, 54, 11, 491130, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 54, 15, 995530, tzinfo=<UTC>)}]>
>>> Ninjas.objects.last()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Ninjas' is not defined
>>> Ninja.objects.last()
<Ninja: Ninja object (20)>
>>> Ninjas.object.first()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Ninjas' is not defined
>>> Ninja.object.first()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: type object 'Ninja' has no attribute 'object'
>>> Ninja.objects.first()
<Ninja: Ninja object (1)>
>>> d1.ninjas.all().values()
<QuerySet [{'id': 12, 'first_name': 'Pizza', 'last_name': 'Margarita', 'dojo_id': 10, 'created_at': datetime.datetime(2021, 3, 22, 3, 46, 48, 70568, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 46, 57, 882867, tzinfo=<UTC>)}, {'id': 13, 'first_name': 'Sausage', 'last_name': 'Peperroni', 'dojo_id': 10, 'created_at': datetime.datetime(2021, 3, 22, 3, 47, 28, 267448, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 47, 37, 21147, tzinfo=<UTC>)}, {'id': 14, 'first_name': 'Vacation', 'last_name': 'Beach', 'dojo_id': 10, 'created_at': datetime.datetime(2021, 3, 22, 3, 48, 9, 819451, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 50, 45, 72288, tzinfo=<UTC>)}]>
>>> d3.ninjas.all().values()
<QuerySet [{'id': 18, 'first_name': 'Weather', 'last_name': 'Sunny', 'dojo_id': 12, 'created_at': datetime.datetime(2021, 3, 22, 3, 53, 22, 515881, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 53, 22, 515881, tzinfo=<UTC>)}, {'id': 19, 'first_name': 'Mexico', 'last_name': 'Mojito', 'dojo_id': 12, 'created_at': datetime.datetime(2021, 3, 22, 3, 53, 46, 714843, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 53, 46, 714843, tzinfo=<UTC>)}, {'id': 20, 'first_name': 'Miami', 'last_name': 'Florida', 'dojo_id': 12, 'created_at': datetime.datetime(2021, 3, 22, 3, 54, 11, 491130, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 54, 15, 995530, tzinfo=<UTC>)}]>
>>> n3.__dict__
{'_state': <django.db.models.base.ModelState object at 0x0000028685996358>, 'id': 20, 'first_name': 'Miami', 'last_name': 'Florida', 'dojo_id': 12, 'created_at': datetime.datetime(2021, 3, 22, 3, 54, 11, 491130, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 3, 22, 3, 54, 15, 995530, tzinfo=<UTC>)}
>>> exit()
